"""create printed_logs

Revision ID: 6ee3390e97d0
Revises: 8c0d1c442352
Create Date: 2025-01-03 11:12:18.006891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ee3390e97d0'
down_revision: Union[str, None] = '8c0d1c442352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('printer_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('volumes', sa.Integer(), nullable=False),
    sa.Column('printed_at', sa.Date(), nullable=True),
    sa.Column('is_reprint', sa.Boolean(), nullable=True),
    sa.Column('reprint_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('printer_logs')
    # ### end Alembic commands ###
