"""upgrade timestamp coluns to br timezone

Revision ID: e24ae35ba3ea
Revises: 195217a3c8fa
Create Date: 2024-12-27 13:24:59.697392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e24ae35ba3ea'
down_revision: Union[str, None] = '195217a3c8fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
